[window]
# opacity = 0.8
# blur = true

[font]
# normal = { family = "BigBlueTermPlus Nerd Font Mono", style = "Regular" }
# normal = { family = "GohuFont 14 Nerd Font Mono", style = "Regular" }
# normal = { family = "UbuntuMono Nerd Font Mono", style = "Regular" }
normal = { family = "DejaVuSansM Nerd Font Mono", style = "Regular" }
size = 14
