#!/bin/bash

#### misc
# wallpaper
feh --bg-scale ~/Pictures/mac_os_catalina.jpg

#### keyboard settings
xset r rate 200 60
setxkbmap "us+bg(bds):2+group(alt_shift_toggle)"
setxkbmap -option caps:escape

#### touchpad settings
# use xinput list-props $TOUCHPAD_ID for more info
# acceleration
xinput set-prop 'ELAN1301:00 04F3:3115 Touchpad' 'libinput Accel Speed' 0.1
xinput set-prop 'ELAN1301:00 04F3:3115 Touchpad' 'libinput Natural Scrolling Enabled' 1
xinput set-prop 'ELAN1301:00 04F3:3115 Touchpad' 'libinput Tapping Enabled' 1 # click
xinput set-prop 'ELAN1301:00 04F3:3115 Touchpad' 'libinput Tapping Drag Enabled' 1 # click

#### Video
# fixes tearing
xrandr --output eDP --set TearFree on
xrandr --output HDMI-A-0 --set TearFree on
xrdb -merge .Xresources


# transperancy
compton -b
