#!/bin/bash

backlights=(/sys/class/backlight/*)
backlight="${backlights[0]}"

if (( ${#backlights[@]} == 0 )); then
	echo "No backlights found in /sys/class/backlight/"
	exit 1
fi

max=$(<"$backlight/max_brightness")

setbl() {
	# $1 should be a percentage (0...100)
	# if max=255 and $1=10, sys_bl_val=25.5
	sys_bl_val=$(echo "scale=10;$1/100*$max" | bc)
	echo $sys_bl_val

	# "%.0f" to round 25.5 to 25
	printf "%.0f" "$sys_bl_val" > "$backlight/brightness"
}

decbl() {
	curr_raw=$(<"$backlight/brightness")
	sys_bl_val=$( echo "scale=10;
		define max(a,b){if(a>b){return(a)}else{return(b)}};
		max($curr_raw/$max-0.1,0)*$max" | bc )
	echo $sys_bl_val

	# "%.0f" to round 25.5 to 25
	printf "%.0f" "$sys_bl_val" > "$backlight/brightness"
}

incbl() {
	curr_raw=$(<"$backlight/brightness")
	sys_bl_val=$( echo "scale=10;
		define min(a,b){if(a<b){return(a)}else{return(b)}};
		min($curr_raw/$max+0.1,1)*$max" | bc )
	echo $sys_bl_val

	# "%.0f" to round 25.5 to 25
	printf "%.0f" "$sys_bl_val" > "$backlight/brightness"
}

while [[ $# -gt 0 ]]; do
	key="$1"
	case $key in
		-s|--set)
		setbl "$2"
		exit 0
		;;
		-i|--inc)
		incbl "$2"
		exit 0
		;;
		-d|--dec)
		decbl "$2"
		exit 0
		;;
		*)    # unknown option
			echo "Unknown option $key"
		;;
	esac
done

