#!/bin/env bash

spacer="  "
mountInfo=""
batInfo=""
memInfo=""
volInfo=""
dateInfo=""
wmHash=""
counter=0

updateMountInfo() {
	line=`df -H | grep /home$`
	all=`echo "$line" | awk '{print $2}'`
	used=`echo "$line" | awk '{print $3}'`
	mountInfo="$used/$all"
}
updateBatteryInfo() {
	cap=`cat /sys/class/power_supply/BAT0/capacity`
	stat=`cat /sys/class/power_supply/BAT0/status`
	color="%{F#6f6}"

	if [[ "$stat" == "Discharging" ]]; then
		if [ $cap -gt 30 ]; then
			color="%{F#66f}"
		else
			color="%{F#f44}"
		fi
	fi

	icon=""
	case $((cap/20)) in
	3) icon="" ;;
	2) icon="" ;;
	1) icon="" ;;
	0) icon="" ;;
	*) icon="" ;;
	esac

	batInfo="$color$icon%{F#fff} $cap"
}
updateMemoryInfo() {
	line=`free -m | head -n 2 | tail -n 1`
	all=`echo $line | awk '{print $2}'`
	used=`echo $line | awk '{print $3}'`
	memInfo="`echo \"100 * $used / $all\" | bc`"
}
updateVolumeInfo() {
	volInfo=`pactl list sinks | grep Volume | head -n 1 | awk '{print $5}'`
}
updateDateInfo() {
	dateInfo=`date '+%d-%m %R'`
}
getWMInfo() {
	echo -n " %{U#8bb745}"
	for i in 1 2 3 4 5 6 7 8 9 0; do
		color=0
		underline=0
		grep -q -E "(F|O)$i" < $tmp
		if [ "$?" == "0" ]; then
			echo -n "%{F#8bb745}"
			color=1
		fi
		grep -q -E "(o|O)$i" < $tmp
		if [ "$?" == "0" ] ; then
			echo -n "%{+u}"
			underline=1
		fi
		echo -n "$i"
		if [ "$color" == "1" ]; then
			echo -n "%{F#ffffff}"
		fi
		if [ "$underline" == "1" ]; then
			echo -n "%{-u}"
		fi
		echo -n " "
	done
}

export tmp=`mktemp`
echo "1" > $tmp
#bspc subscribe desktop_focus | (while true; do read p; echo ${p: -1} > $tmp; done) &
bspc subscribe | (while true; do read p; echo "$p" > $tmp; done) &

while true; do
	((counter++))
	newText=false

	old=$wmHash
	wmHash=`md5sum $tmp`

	if [ "$old" != "$wmHash" ]; then
		wmInfo=$(getWMInfo)
		newText=true
	fi

	if [ $((counter%20)) -eq 0 ]; then
		oldBatInfo=$batInfo
		oldMemInfo=$memInfo
		oldDateInfo=$dateInfo

		updateBatteryInfo
		updateMemoryInfo
		updateDateInfo

		if [ "$oldBatInfo" != "$batInfo" ]; then newText=true; fi
		if [ "$oldMemInfo" != "$memInfo" ]; then newText=true; fi
		if [ "$oldDateInfo" != "$dateInfo" ]; then newText=true; fi
	fi
	if [ $((counter%4)) -eq 0 ]; then
		oldVolInfo=$volInfo
		updateVolumeInfo
		if [ "$oldVolInfo" != "$volInfo" ]; then newText=true; fi
	fi

	if [ $((counter%200)) -eq 0 ]; then
		#oldMountInfo=$mountInfo
		#updateMountInfo
		#if [ "$oldMountInfo" != "$mountInfo" ]; then newText=true; fi

		counter=0
	fi

	if [ "$newText" = true ]; then
		echo -n "%{B#000}"

		##### left
		echo -n "%{l}"
		echo -n "$wmInfo"

		##### center
		echo -n "%{c}"

		# date
		echo -n "$spacer$dateInfo$spacer"

		##### right
		echo -n "%{r}"

		# vol
		echo -n "$spacer $volInfo$spacer"

		# mem
		echo -n "$spacer $memInfo%$spacer"

		# bat
		echo -n "$spacer$batInfo%$spacer"

		# hd
		#echo -n "$spacer⛁ $mountInfo$spacer"

		echo ""
	fi

	sleep 0.05
done
