#!/bin/env bash

source="$1"
input="$2"

if [[ "$source" == "" ]]; then
	echo "Missing source filename."
	exit 1
fi

#echo "==== Compilation started ===="
c++ -std=c++14 -Wpedantic -lpthread -O2 "$source.cpp" -o "$source" -DLOCAL_STJO
#echo "==== Compilation ended ===="

#if [[ "$input" == "" ]]; then
	#./"$source"
#else
	#time ./"$source" < "$input" > ".$input.out"
	#md5sum ".$input.out"
#fi

#echo "==== Done ===="
