#!/bin/env python
import sys

data = sys.stdin.read()

i = 0
out = ""

while True:
    if i + 1 < len(data):
        if(data[i] == '\\'):
            if(data[i+1] == '\\'):
                out += '\\'
            elif(data[i+1] == 'n'):
                out += '\n'
            elif(data[i+1] == 't'):
                out += '\t'
            elif(data[i+1] == '\''):
                out += '\''
            i += 1
        else:
            out += data[i]
    i += 1
    if i >= len(data):
        break

print(out[:-1]) # remove the last '
