#!/bin/env bash

if [[ "$1" == "all" ]]; then
	for i in *
	do
		d=`date -d @$i`

		echo "==========================="
		echo "$d - $i - `cat $i | head -n 7 | tail -n 1 | cut -c 3-`"
		echo ""
		cat $i | tail -n 5 | head -n 1 | cut -c 3- | cmsfix
	done;
elif [[ "$1" == "" ]]; then
	for i in *
	do
		d=`date -d @$i`
		echo "$d - $i - `cat $i | head -n 7 | tail -n 1 | cut -c 3-`"
	done;
else
	cat "$1" | tail -n 5 | head -n 1 | cut -c 3- | cmsfix
fi
