#!/bin/env bash

if (( $# < 1 ))
then
	echo "No source file given"
	exit
fi

mkdir downloads
name='idk'

cat $1 | while read i
do
	if [[ "$i" == "" ]]; then continue; fi

	first=${i:0:1}
	if [[ "$first" == "#" ]];
	then
		name=${i:2:`echo $i | wc -c`}
		echo "New Category: $name"
		mkdir downloads/$name
		continue;
	fi

	pushd . &> /dev/null
	cd downloads/$name;
	youtube-dl -i -x --audio-quality 0 --audio-format opus $i
	popd &> /dev/null
done

# example input, prefixed with "### "

### # eminem
### https://www.youtube.com/watch?v=ytQ5CYE1VZw
### https://www.youtube.com/watch?v=XbGs_qK2PQA
###
### # glitch_mob
### https://www.youtube.com/watch?v=-m7e7tCn7Bk
### https://www.youtube.com/watch?v=HVpY_qIPM34
### https://www.youtube.com/watch?v=lN_MSyrq6-U
###
### # imagine_dragons
### https://www.youtube.com/watch?v=ktvTqknDobU
###
### # epic_rap_battles-season_5
### https://www.youtube.com/playlist?list=PLQ-7WiWmOuK9ihqYG20uqClZWaM6CIDtf

