#!/bin/sh

tmpImgName=`mktemp`".png"

# Take a picture of the screen
imlib2_grab $tmpImgName

# Blur it a little bit
convert $tmpImgName -blur 6x3 $tmpImgName

# Start i3lock and put the blurred image as a background
i3lock -fi $tmpImgName

if [ "$1" == "suspend" ]
then
	systemctl suspend
fi

# Delete the junk
rm $tmpImgName
