#!/bin/bash

TMPBG=/tmp/screen.png
LOCK=$HOME/.hax/lock.png
RES=$(xrandr | grep '*' | sed -E "s/[^0-9]*([0-9]+)x([0-9]+).*/\1*\2/")

v="noise=alls=10,scale=iw*.05:-1,scale=iw*20:-1:flags=neighbor"
ffmpeg -f x11grab -video_size $RES -y -i $DISPLAY -i $LOCK \
	-filter_complex "boxblur=3:2,overlay=(main_w-overlay_w)/2:(main_h-overlay_h)/2" \
	-vframes 1 $TMPBG -loglevel quiet

setxkbmap "us"

if [ "$1" == "suspend" ]
then
	i3lock -i $TMPBG
	systemctl suspend
else
	i3lock -ni $TMPBG
fi

rm $TMPBG
setxkbmap "us+bg(bds):2+group(alt_shift_toggle)"
