#!/bin/env sh
#feh --bg-tile ~/wallpapers/generated/bubbles.png
#feh --bg-tile ~/wallpapers/hdwallpapers/the-next-polylog-wallpaper-for-1920x1080-63-673.jpg
feh --bg-scale ~/wallpapers/hdwallpapers/wolf-howling-at-the-moon-wallpaper-for-1920x1080-63-944.jpg
