#!/bin/bash

gentest="$1"
bin1="$2"
bin2="$3"
threads="$4"

if [[ "$threads" == "" ]]; then
	threads=4
fi

tmp=`mktemp -d -t tochki_XXXX`
echo "Starting in $tmp..."

test() {
	dir="$tmp/$1"
	mkdir "$dir"

	while true; do
		"$gentest" > "$dir/test"
		"$bin1" < "$dir/test" > "$dir/b1"
		"$bin2" < "$dir/test" > "$dir/b2"

		diff -q "$dir/b1" "$dir/b2" > /dev/null
		if [[ "$?" != "0" ]]; then
			printf "\x1b[K"
			echo "[ diff $tmp $1 ]"
			echo "."
			exit 0
		fi

		flock "$tmp/status" -c "printf '.' >> $tmp/status && printf '\x1b[1A\x1b[K' && wc -c $tmp/status"
	done
}

for ((t=0;t<threads;t++)); do
	test $t &
done

for job in `jobs -p`; do
	wait $job
done
