#!/bin/env bash

# __FCKDUP__ get current volume
curr=`pactl list sinks | grep Volume | head -n 1 | awk '{print $5}'`

# trim the '%' sign
curr=${curr::-1}

if [[ "$1" == "" ]]; then
	echo "$curr"
elif [[ "$1" == "inc" ]]; then
	pactl set-sink-volume @DEFAULT_SINK@ `echo $curr + 5 | bc`%
elif [[ "$1" == "dec" ]];  then
	pactl set-sink-volume @DEFAULT_SINK@ `echo $curr - 5 | bc`%
fi
