#!/bin/env bash

dir="$1"
if [ "$dir" == "" ]
then
	echo "test"
	dir="./"
fi

for file in $dir/*.webm
do
	echo "Running on: $file"
	nname=`echo "$file" | sed "s/ /-/g" | sed "s/.webm/.opus/g" | sed "s/.--Epic-Rap-Battles-of-History/-ERB/g"`
	echo "$nname"
	ffmpeg -loglevel 8 -i "$file" -f opus "$nname"
done;

echo "Don't forget to delete the .webm files"
